# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Nam nguyen
title: Data Engineer
email: hainam.nguyen.ict@gmail.com
website: https://namndh.github.io

darkmode: true

# Social links
# twitter_username: facespics
github_username:  namndh
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: __namnguyen
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Nam and I am a junior data engineer. I also have experience in developing machine learning and deep learning application. I have worked at a number of companies gaining teamwork and leadership skills.
  
  I am most skilled in: <mark>Python</mark>, <mark>PySpark</mark>, <mark>Pytorch</mark> and <mark>OpenCV</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data and software engineering some of my other interests and hobbies are:
   - Gym
   - Gaming
   - Pool Billiard

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag